#pragma once

enum class PoliciesType
{
	policy_unknown = -1,
	policy_front_old_guard,
	policy_front_archives,
	policy_front_asket,
	policy_front_bank,
	policy_front_central_government,
	policy_front_coloss,
	policy_front_contribution,
	policy_front_corinthian_order,
	policy_front_diolk,
	policy_front_diversification,
	policy_front_evpalin_tunnel,
	policy_front_gold_reserve,
	policy_front_gradualism,
	policy_front_greek_fire,
	policy_front_helepolis,
	policy_front_high_tax,
	policy_front_hire_mercenay,
	policy_front_lighthouse,
	policy_front_lyceum_foundation,
	policy_front_mint,
	policy_front_oracle,
	policy_front_ostracism,
	policy_front_painter_standing,
	policy_front_peripter,
	policy_front_persia,
	policy_front_power,
	policy_front_proscenium,
	policy_front_public_market,
	policy_front_rare_collection,
	policy_front_reform,
	policy_front_rivalvary,
	policy_front_science_respect,
	policy_front_silver_mine,
	policy_front_soviet,
	policy_front_stadium,
	policy_front_statue_hall,
	policy_front_stone_mine,
	policy_front_supplies_from_overseas,
	policy_front_western_gifts,
	policy_front_amnesty_for_socrat,
	policies_end,
	policies_count = policies_end
};

const char* ToString(PoliciesType evt);
