#ifndef __EditorMainWindow__
#define __EditorMainWindow__

/**
@file
Subclass of EditorMainWindowBase, which is generated by wxFormBuilder.
*/

#include <filesystem>
#include "vsgEditor.h"
#include "ViewerWindow.h"
#include "../DataModel.h"

//// end generated include

/** Implementing EditorMainWindowBase */
class EditorMainWindow : public EditorMainWindowBase, public IDataModelObserver
{
public
    
    
    :
    EditorMainWindow(IDataModelEditor* dataModel, int argc, char** argv, wxWindow* parent);
    void Paint();

    void Execute(const CompileCommand& cmd) override;

protected:
    
    void OnImport(wxCommandEvent& event) override;
    void assetsTreeOnTreeSelChanged(wxTreeEvent& event) override;
    
    /*void assetsTreeOnTreeBeginDrag(wxTreeEvent& event) override;
    void assetsTreeOnTreeEndDrag(wxTreeEvent& event) override;
    void finalSceneOnTreeBeginDrag(wxTreeEvent& event) override;
    void finalSceneOnTreeEndDrag(wxTreeEvent& event) override;*/

    virtual void assetsTreeOnTreeBeginDrag(wxTreeEvent& event) override;
    virtual void assetsTreeOnTreeEndDrag(wxTreeEvent& event) override;
    virtual void finalSceneOnTreeSelChanged(wxTreeEvent& event) override;
    virtual void finalSceneOnTreeBeginDrag(wxTreeEvent& event) override;
    virtual void finalSceneOnTreeEndDrag(wxTreeEvent& event) override;
    virtual void deleteFromSceneOnButtonClick(wxCommandEvent& event) override;
    virtual void loadProjectMenuItemOnMenuSelection(wxCommandEvent& event) override;
    virtual void saveProjectMenuItemOnMenuSelection(wxCommandEvent& event) override;
    virtual void resetMenuItemOnMenuSelection(wxCommandEvent& event) override;

private:
    bool reseting{ false };
    ViewerWindow* viewerWindow;
    std::filesystem::path _projectStorage;
    vsg::ref_ptr<vsg::Group> _root = vsg::Group::create();

    IDataModelEditor* _dataModel;
    vsg::ref_ptr<vsg::Options> _options;    

    struct Package {
        wxTreeItemId Root;
        wxTreeItemId Transforms;
        wxTreeItemId Geometries;
        wxTreeItemId Materials;
        vsg::ref_ptr<vsg::Node> RootNode;
    };

    std::unordered_map<std::string, Package> packageToId;

    // void Execute(const SetRootNodeCommand& cmd) override;
    void Execute(const ItemAddedNotification& cmd) override;
    void Execute(const ItemRemovedNotification& cmd) override;

    // Inherited via IDataModelObserver
    void Execute(const SceneCompeledNotification& cmd) override;

    EntryPath _oldPath;

    // Inherited via IDataModelObserver
    void Execute(const ModelResetNotification& cmd) override;

    // Inherited via IDataModelObserver
    void Execute(const LogNotification& cmd) override;
};

#endif // __EditorMainWindow__
