#ifndef __EditorMainWindow__
#define __EditorMainWindow__

/**
@file
Subclass of EditorMainWindowBase, which is generated by wxFormBuilder.
*/

#include <filesystem>
#include "vsgEditor.h"
#include "ViewerWindow.h"
#include "TransformPanel.h"
#include "../DataModel.h"

//// end generated include
class ConfigEntry;

/** Implementing EditorMainWindowBase */
class EditorMainWindow : public EditorMainWindowBase, public IDataModelObserver
{
public:

    EditorMainWindow(IDataModelEditor* dataModel, int argc, char** argv, wxWindow* parent);
    void Paint();

    void Execute(const CompileCommand& cmd) override;

protected:
    
    void OnImport(wxCommandEvent& event) override;
    void assetsTreeOnTreeSelChanged(wxTreeEvent& event) override;
    
    /*void assetsTreeOnTreeBeginDrag(wxTreeEvent& event) override;
    void assetsTreeOnTreeEndDrag(wxTreeEvent& event) override;
    void finalSceneOnTreeBeginDrag(wxTreeEvent& event) override;
    void finalSceneOnTreeEndDrag(wxTreeEvent& event) override;*/

    void assetsTreeOnTreeBeginDrag(wxTreeEvent& event) override;
    void assetsTreeOnTreeEndDrag(wxTreeEvent& event) override;
    void finalSceneOnTreeSelChanged(wxTreeEvent& event) override;
    void finalSceneOnTreeBeginDrag(wxTreeEvent& event) override;
    void finalSceneOnTreeEndDrag(wxTreeEvent& event) override;
    void finalSceneOnTreeItemRightClick(wxTreeEvent& event) override;
    void deleteFromSceneOnButtonClick(wxCommandEvent& event) override;
    void loadProjectMenuItemOnMenuSelection(wxCommandEvent& event) override;
    void saveProjectMenuItemOnMenuSelection(wxCommandEvent& event) override;
    void resetMenuItemOnMenuSelection(wxCommandEvent& event) override;
    void finalSceneOnTreeBeginLabelEdit(wxTreeEvent& event) override;void finalSceneOnTreeEndLabelEdit(wxTreeEvent& event) override;
    void finalSceneOnKeyDown(wxKeyEvent& event) override;
    void showTransformMenuOnMenuSelection(wxCommandEvent& event) override;
    void addToSceneOnCombobox(wxCommandEvent& event) override;
    void navigateOnToolClicked(wxCommandEvent& event) override;
    void exportMenuOnMenuSelection(wxCommandEvent& event) override;
    void langAddOnButtonClick(wxCommandEvent& event);
    void langRemoveOnButtonClick(wxCommandEvent& event);
    void languageListBoxOnListBox(wxCommandEvent& event);
    void languageListBoxOnListBoxDClick(wxCommandEvent& event);

private:
    
    int GetEntryTypeImage(EntryType type);
    void UpdateConfig();
    std::vector<std::pair<std::int32_t, vsg::ref_ptr<vsg::Node>>> _cleanup;

    bool reseting{ false };
    ViewerWindow* viewerWindow;
    std::filesystem::path _projectStorage;
    vsg::ref_ptr<vsg::Group> _root = vsg::Group::create();
    vsg::ref_ptr<vsg::Camera> _camera;
    vsg::ref_ptr<vsg::LookAt> _lookAt;
    vsg::ref_ptr<vsg::Trackball> _trackball;
    std::shared_ptr<TransformPanel> _transformPanel{ nullptr };
    std::shared_ptr<ConfigEntry> _config;
    wxImageList* _imageList;
    int _imageErrorIcon;
    int _imageTransformImage;
    int _imageGroupImage;
    int _imageGeometryImage;
    int _imageMaterialImage;
    int _imageLocalizedImage;

    IDataModelEditor* _dataModel;
    vsg::ref_ptr<vsg::Options> _options;    

    struct Package {
        wxTreeItemId Root;
        wxTreeItemId Transforms;
        wxTreeItemId Geometries;
        wxTreeItemId Materials;
        vsg::ref_ptr<vsg::Node> RootNode;
    };

    std::unordered_map<std::string, Package> packageToId;

    // void Execute(const SetRootNodeCommand& cmd) override;
    void Execute(const ItemAddedNotification& cmd) override;
    void Execute(const ItemRemovedNotification& cmd) override;

    // Inherited via IDataModelObserver
    void Execute(const SceneCompeledNotification& cmd) override;

    EntryPath _oldPath;

    // Inherited via IDataModelObserver
    void Execute(const ModelResetNotification& cmd) override;

    // Inherited via IDataModelObserver
    void Execute(const LogNotification& cmd) override;

    // Inherited via IDataModelObserver
    void Execute(const EntrySelectedNotification& cmd) override;

    // Inherited via IDataModelObserver
    void Execute(const EntryPropertyChangedNotification& cmd) override;

    // Inherited via IDataModelObserver
    void Execute(const ConfigNotification& cmd) override;

    // Inherited via IDataModelObserver
    void Execute(const LanguageAddedNotification& cmd) override;
    void Execute(const LanguageRemoveNotification& cmd) override;

    // Inherited via IDataModelObserver
    void Execute(const SuggestedChildrenNotification& cmd) override;
};

#endif // __EditorMainWindow__
