#ifndef __TextEnterDialog__
#define __TextEnterDialog__

/**
@file
Subclass of TextEnter, which is generated by wxFormBuilder.
*/

#include "vsgEditor.h"

//// end generated include

/** Implementing TextEnter */
class TextEnterDialog : public TextEnter
{
public:
    /** Constructor */
    TextEnterDialog(wxWindow* parent);

	wxString GetText() const;
protected:
	
	void textEditOnText(wxCommandEvent& event);
	void btnOkOnButtonClick(wxCommandEvent& event);
	void btnCancelOnButtonClick(wxCommandEvent& event);

};

#endif // __TextEnterDialog__
